# -*- coding: utf-8 -*-
"""Anagram Solver.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebook#fileId=1IwwgXE5WQWSAOAGu3dSrjeYY-fexJC7C
"""

def anagramcheck(word,checkword):
  for letter in word:
        if letter in checkword:
          
            checkword=checkword.replace(letter, '', 1)

        else:
            return 0
  return 1

wordin=raw_input('Enter anagram:\n')



